version: '3.8'

services:
  # MongoDB データベース
  mongodb:
    image: mongo:7.0
    container_name: constella-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-password}
      MONGO_INITDB_DATABASE: constella
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - constella-network

  # Python FastAPI バックエンド
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: constella-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      PYTHONUNBUFFERED: 1
      MONGODB_URL: mongodb://${MONGO_ROOT_USERNAME:-admin}:${MONGO_ROOT_PASSWORD:-password}@mongodb:27017/constella?authSource=admin
      OLLAMA_API_URL: ${OLLAMA_API_URL:-http://192.168.1.7:11434}
      OLLAMA_MODEL: ${OLLAMA_MODEL:-gpt-oss:20B}
      UPLOAD_DIR: /app/uploads
    volumes:
      - ./backend:/app
      - ./.env:/app/.env
      - ./credentials:/app/credentials:ro
      - uploads:/app/uploads
    depends_on:
      - mongodb
    networks:
      - constella-network
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  # React フロントエンド
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: constella-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: ${NODE_ENV:-development}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - constella-network
    command: npm start

  # Mongo Express (MongoDB管理UI) - 開発用
  mongo-express:
    image: mongo-express:latest
    container_name: constella-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME:-admin}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD:-password}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USERNAME:-admin}:${MONGO_ROOT_PASSWORD:-password}@mongodb:27017/
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
      - mongodb
    networks:
      - constella-network

networks:
  constella-network:
    driver: bridge

volumes:
  mongodb_data:
  mongodb_config:
  uploads: